
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Don't touch unless you are told to
	debug_packet = false

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

	[general.types]

		[general.types.wood_type]

			[general.types.wood_type.ars_nouveau]
				archwood = true

			[general.types.wood_type.biomesoplenty]
				fir = true
				redwood = true
				mahogany = true
				jacaranda = true
				palm = true
				willow = true
				dead = true
				magic = true
				umbran = true
				hellbark = true

			[general.types.wood_type.aether]
				skyroot = true

		[general.types.leaves_type]

			[general.types.leaves_type.ars_nouveau]
				blue_archwood = true
				green_archwood = true
				purple_archwood = true
				red_archwood = true

			[general.types.leaves_type.biomesoplenty]
				origin = true
				flowering_oak = true
				maple = true
				orange_autumn = true
				yellow_autumn = true
				rainbow_birch = true
				snowblossom = true
				fir = true
				redwood = true
				mahogany = true
				jacaranda = true
				palm = true
				willow = true
				dead = true
				magic = true
				umbran = true
				hellbark = true

			[general.types.leaves_type.croptopia]
				cinnamon = true

			[general.types.leaves_type.aether]
				skyroot = true
				golden_oak = true
				crystal = true
				crystal_fruit = true
				holiday = true
				decorated_holiday = true

		[general.types.cake]

			[general.types.cake.createaddition]
				chocolate_cake = true
				honey_cake = true

	[general.entries]

		[general.entries.wood_type]

			[general.entries.wood_type.mcwroofs]
				planks_upper_steep_roof = true
				top_roof = true
				lower_roof = true
				planks_roof = true
				upper_steep_roof = true
				steep_roof = true
				upper_lower_roof = true
				attic_roof = true
				planks_upper_lower_roof = true
				roof = true
				planks_attic_roof = true
				planks_top_roof = true
				planks_steep_roof = true
				planks_lower_roof = true

			[general.entries.wood_type.mcwfurnitures]
				stripped_glass_table = true
				stripped_desk = true
				end_table = true
				stool_chair = true
				stripped_lower_triple_drawer = true
				stripped_drawer_counter = true
				bookshelf_drawer = true
				double_drawer = true
				stripped_coffee_table = true
				stripped_counter = true
				stripped_striped_chair = true
				covered_desk = true
				stripped_stool_chair = true
				stripped_modern_wardrobe = true
				cupboard_counter = true
				stripped_covered_desk = true
				coffee_table = true
				glass_table = true
				stripped_cupboard_counter = true
				stripped_triple_drawer = true
				stripped_chair = true
				stripped_double_drawer_counter = true
				stripped_modern_desk = true
				stripped_bookshelf_cupboard = true
				modern_wardrobe = true
				lower_bookshelf_drawer = true
				striped_chair = true
				stripped_large_drawer = true
				wardrobe = true
				modern_desk = true
				stripped_lower_bookshelf_drawer = true
				stripped_end_table = true
				drawer = true
				stripped_bookshelf_drawer = true
				stripped_bookshelf = true
				modern_chair = true
				chair = true
				stripped_table = true
				double_drawer_counter = true
				drawer_counter = true
				counter = true
				stripped_modern_chair = true
				bookshelf_cupboard = true
				table = true
				desk = true
				stripped_double_wardrobe = true
				stripped_double_drawer = true
				triple_drawer = true
				lower_triple_drawer = true
				bookshelf = true
				stripped_wardrobe = true
				large_drawer = true
				double_wardrobe = true
				stripped_drawer = true

			[general.entries.wood_type.mcwtrpdoors]
				ranch_trapdoor = true
				beach_trapdoor = true
				swamp_trapdoor = true
				glass_trapdoor = true
				blossom_trapdoor = true
				tropical_trapdoor = true
				cottage_trapdoor = true
				paper_trapdoor = true
				bark_trapdoor = true
				classic_trapdoor = true
				bamboo_trapdoor = true
				barn_trapdoor = true
				four_panel_trapdoor = true
				barred_trapdoor = true
				mystic_trapdoor = true
				barrel_trapdoor = true

			[general.entries.wood_type.mcwwindows]
				louvered_shutter = true
				plank_pane_window = true
				plank_four_window = true
				stripped_log_window2 = true
				log_parapet = true
				window2 = true
				stripped_log_four_window = true
				stripped_log_window = true
				plank_window = true
				plank_window2 = true
				pane_window = true
				stripped_pane_window = true
				four_window = true
				plank_parapet = true
				blinds = true
				window = true
				shutter = true

			[general.entries.wood_type.mcwdoors]
				japanese2_door = true
				tropical_door = true
				barn_glass_door = true
				four_panel_door = true
				beach_door = true
				waffle_door = true
				japanese_door = true
				stable_door = true
				modern_door = true
				nether_door = true
				stable_head_door = true
				cottage_door = true
				western_door = true
				paper_door = true
				bamboo_door = true
				swamp_door = true
				glass_door = true
				barn_door = true
				mystic_door = true
				bark_glass_door = true
				classic_door = true

			[general.entries.wood_type.mcwfences]
				highley_gate = true
				picket_fence = true
				stockade_fence = true
				wired_fence = true
				horse_fence = true
				pyramid_gate = true

			[general.entries.wood_type.mcwbridges]
				bridge_pier = true
				rope_bridge = true
				log_bridge_middle = true
				rope_bridge_stair = true
				log_bridge_stair = true
				rail_bridge = true

			[general.entries.wood_type.mcwpaths]
				planks_path = true

			[general.entries.wood_type.decorative_blocks]
				seat = true
				palisade = true
				beam = true
				support = true

			[general.entries.wood_type.farmersdelight]
				cabinet = true

			[general.entries.wood_type.mcwlights]
				tiki_torch = true
				soul_tiki_torch = true

			[general.entries.wood_type.twigs]
				table = true

			[general.entries.wood_type.create]
				window_pane = true
				window = true

		[general.entries.leaves_type]

			[general.entries.leaves_type.mcwfences]
				hedge = true

